Sources/AddressBook/AddressBook/Controllers/AddressBookController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using DataAccessLayer;

namespace AddressBook.Controllers
{
    [Authorize]
    public class AddressBookController : Controller
    {
        private readonly AddressBookEntities _db;

        public AddressBookController(AddressBookEntities db)
        {
            _db = db;
        }

        // GET: AddressBook
        public ActionResult Index(string search)
        {
            var contacts = _db.Contact.AsQueryable();

            if (!string.IsNullOrEmpty(search))
            {
                contacts =
                    contacts.Where(x => 
                        x.Address.Contains(search) ||
                        x.FirstName.Contains(search) || x.LastName.Contains(search) ||
                        string.Concat(x.FirstName, " ", x.LastName).Contains(search) ||
                        x.EmailAddress.Any(e => e.Email.Contains(search)) ||
                        x.PhoneNumber.Any(p => p.PhoneNumber1.Contains(search))
                    );
            }

            return View(contacts.Take(50).ToList());
        }

        // GET: AddressBook/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = _db.Contact.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: AddressBook/Create
        public ActionResult Create()
        {
            var model = new Contact();
            return View(model);
        }

        // POST: AddressBook/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Contact contact)
        {
            if (ModelState.IsValid)
            {
                _db.Contact.Add(contact);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contact);
        }

        // GET: AddressBook/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = _db.Contact.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: AddressBook/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind] Contact contact)
        {
            if (ModelState.IsValid)
            {
                var contactNumbers =
                    _db.PhoneNumber.Where(x => x.ContactId == contact.ContactId);

                var currentPhoneNumberIds = contact.PhoneNumber.Select(c => c.PhoneNumberId);

                var deletedNumbers =
                    contactNumbers.Where(x => !currentPhoneNumberIds.Contains(x.PhoneNumberId)).ToList();

                _db.PhoneNumber.RemoveRange(deletedNumbers);

                foreach (var phoneNumber in contact.PhoneNumber)
                {
                    
                    _db.PhoneNumber.AddOrUpdate(phoneNumber);
                }
                contact.PhoneNumber = new HashSet<PhoneNumber>();

                var contactEmails =
                    _db.EmailAddress.Where(x => x.ContactId == contact.ContactId);

                var currentEmailIds = contact.EmailAddress.Select(c => c.EmailAddressId).ToArray();

                var deletedEmails =
                    contactEmails.Where(x => !currentEmailIds.Contains(x.EmailAddressId));

                _db.EmailAddress.RemoveRange(deletedEmails);

                foreach (var email in contact.EmailAddress)
                {

                    _db.EmailAddress.AddOrUpdate(email);
                }
                contact.EmailAddress = new HashSet<EmailAddress>();


                _db.Entry(contact).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Details", new { id = contact.ContactId});
            }
            return View(contact);
        }

        // GET: AddressBook/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = _db.Contact.Find(id);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // POST: AddressBook/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contact contact = _db.Contact.Find(id);
            _db.Contact.Remove(contact);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult CreatePhoneNumber(int? contactId)
        {
            var model = new PhoneNumber();
            if (contactId.HasValue)
                model.ContactId = contactId.Value;

            return PartialView("~/Views/Shared/EditorTemplates/PhoneNumber.cshtml", model);
        }

        public PartialViewResult CreateEmailAddress(int? contactId)
        {
            var model = new EmailAddress();
            if (contactId.HasValue)
                model.ContactId = contactId.Value;

            return PartialView("~/Views/Shared/EditorTemplates/EmailAddress.cshtml", model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sources/AddressBook/AddressBook/Views/AddressBook/Create.cshtml
@using DataAccessLayer
@model DataAccessLayer.Contact

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<PhoneNumber> phoneNumbers = Model.PhoneNumber.ToList();
    List<EmailAddress> emails = Model.EmailAddress.ToList();
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "AddressBook", FormMethod.Post, new { id = "createForm"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Address, "", new {@class = "text-danger"})
            </div>
        </div>

        <div id="phoneNumbers">
            @for (int i = 0; i < phoneNumbers.Count; i++)
            {
                @Html.EditorFor(f => phoneNumbers[i])
            }
        </div>
        <div class="form-group">
            <div class="col-md-3 col-md-offset-2">
               
                @Ajax.ActionLink("Add Phone Number", "CreatePhoneNumber", null, new AjaxOptions
           {
               HttpMethod = "GET",
               InsertionMode = InsertionMode.InsertAfter,
               UpdateTargetId = "phoneNumbers",
               OnSuccess = "onItemAddSuccess",
               LoadingElementId = "loadingPhone"
           }, new {@class = "btn btn-default"})
                <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate loading" id="loadingPhone" style="display: none"></span>
            </div>
        </div>

        <div id="emailAddresses">
            @for (int i = 0; i < emails.Count; i++)
            {
                @Html.EditorFor(f => emails[i])
            }
        </div>

        <div class="form-group">
            <div class="col-md-3 col-md-offset-2">
                @Ajax.ActionLink("Add Email Address", "CreateEmailAddress", null, new AjaxOptions
           {
               HttpMethod = "GET",
               InsertionMode = InsertionMode.InsertAfter,
               UpdateTargetId = "emailAddresses",
               OnSuccess = "onItemAddSuccess",
               LoadingElementId = "loadingEmail"
           }, new { @class = "btn btn-default" })
                <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate loading" id="loadingEmail" style="display: none"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/editContact")
}

Sources/AddressBook/AddressBook/Views/AddressBook/Delete.cshtml
@model DataAccessLayer.Contact

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
    <div class="col-md-6">
        <table class="table table-bordered table-striped table-condensed">
            <tr>
                <th>
                    @Html.DisplayName("Phone number")
                </th>
            </tr>

            @foreach (var item in Model.PhoneNumber)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber1)
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="col-md-6">
        <table class="table table-bordered table-striped table-condensed">
            <tr>
                <th>
                    @Html.DisplayName("Email Address")
                </th>
            </tr>

            @foreach (var item in Model.EmailAddress)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="clearfix"></div>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Sources/AddressBook/AddressBook/Views/AddressBook/Details.cshtml
@model DataAccessLayer.Contact

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Contact</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<div class="col-md-6">
    <table class="table table-bordered table-striped table-condensed">
        <tr>
            <th>
                @Html.DisplayName("Phone number")
            </th>
        </tr>

        @foreach (var item in Model.PhoneNumber)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber1)
                </td>
            </tr>
        }
    </table>
</div>
<div class="col-md-6">
    <table class="table table-bordered table-striped table-condensed">
        <tr>
            <th>
                @Html.DisplayName("Email Address")
            </th>
        </tr>

        @foreach (var item in Model.EmailAddress)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
            </tr>
        }
    </table>
</div>
<div class="clearfix"></div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ContactId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Sources/AddressBook/AddressBook/Views/AddressBook/Edit.cshtml
@using DataAccessLayer
@model DataAccessLayer.Contact

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<PhoneNumber> phoneNumbers = Model.PhoneNumber.ToList();
    List<EmailAddress> emails = Model.EmailAddress.ToList();
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ContactId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Address, "", new {@class = "text-danger"})
            </div>
        </div>

        <div id="phoneNumbers">
            @for (int i = 0; i < phoneNumbers.Count; i++)
            {
                @Html.EditorFor(f => phoneNumbers[i])
            }
        </div>
        <div class="form-group">
            <div class="col-md-3 col-md-offset-2">
                @Ajax.ActionLink("Add Phone Number", "CreatePhoneNumber", new { contactId = Model.ContactId}, new AjaxOptions
           {
               HttpMethod = "GET",
               InsertionMode = InsertionMode.InsertAfter,
               UpdateTargetId = "phoneNumbers",
               OnSuccess = "onItemAddSuccess",
               LoadingElementId = "loadingPhone"
           }, new { @class = "btn btn-default" })
                <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate loading" id="loadingPhone" style="display: none"></span>
            </div>
        </div>

        <div id="emailAddresses">
            @for (int i = 0; i < emails.Count; i++)
            {
                @Html.EditorFor(f => emails[i])
            }
        </div>

        <div class="form-group">
            <div class="col-md-3 col-md-offset-2">
                @Ajax.ActionLink("Add Email Address", "CreateEmailAddress", new { contactId = Model.ContactId }, new AjaxOptions
           {
               HttpMethod = "GET",
               InsertionMode = InsertionMode.InsertAfter,
               UpdateTargetId = "emailAddresses",
               OnSuccess = "onItemAddSuccess",
               LoadingElementId = "loadingEmail"
           }, new { @class = "btn btn-default" })
                <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate loading" id="loadingEmail" style="display: none"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/editContact")
}

Sources/AddressBook/AddressBook/Views/AddressBook/Index.cshtml
@model IEnumerable<DataAccessLayer.Contact>

@{
    ViewBag.Title = "Contacts";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string querySearch = Context.Request.QueryString == null ? "" : Context.Request.QueryString["search"] ?? "";
}

<h2>Contacts</h2>

<div class="row mb-10">
    <div class="col-xs-3">
        @Html.ActionLink("Create New", "Create", null, new {@class = "btn btn-default"})
    </div>
    <div class="col-xs-8 pull-right">
        @using (Html.BeginForm("Index", "AddressBook", FormMethod.Get, new {@class = "form-inline pull-right", id = "searchForm"}))
        {
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control pull-right" name="search" id="search" placeholder="Search for.." value="@querySearch">
                    <span class="input-group-btn">
                        <input class="btn btn-secondary" type="submit" value="Go!"/>
                        <button class="btn btn-secondary ml-5" onclick="$('#search').val(''); $('#searchForm').submit();">Clear</button>
                    </span>
                </div>

            </div>
        }
    </div>
</div>
<table class="table table-bordered table-striped table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ContactId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ContactId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ContactId })
        </td>
    </tr>
}

</table>